Imports System.Web.Script.Serialization
Imports QRCoder
Imports System.Net
Imports System.Drawing
Imports System.IO

Partial Class eblDefault
  Inherits System.Web.UI.Page

  Private Sub cmdClearTax_Click(sender As Object, e As EventArgs) Handles cmdClearTax.Click
    Label2.Text = ""

    Dim u As Uri = New Uri("https://einvoicing.internal.cleartax.co/v1/govt/api/Invoice")
    Dim x As HttpWebRequest = WebRequest.Create(u)
    With x
      .Method = "POST"
      .ContentType = "application/json"
      .Headers.Add("gstin", "29AAFCD5862R000")
      .Headers.Add("owner_id", "c8ea1eb9-47b3-47e3-848d-258178305635")

      .Accept = "*/*"
      .CachePolicy = New Cache.RequestCachePolicy(Net.Cache.RequestCacheLevel.NoCacheNoStore)
      .Headers.Add("mode", "no-cors")
      .KeepAlive = True

    End With
    Dim jsonStr As String = New JavaScriptSerializer().Serialize(New clearTaxRequest)
    Dim jsonByte() As Byte = Encoding.ASCII.GetBytes(jsonStr)
    x.ContentLength = jsonByte.Count
    x.GetRequestStream().Write(jsonByte, 0, jsonByte.Count)
    Try
      Dim rs As WebResponse = x.GetResponse()
      Dim st As IO.Stream = rs.GetResponseStream
      Dim sr As IO.StreamReader = New IO.StreamReader(st)
      Dim strResponse As String = sr.ReadToEnd
      sr.Close()
      Label2.Text = strResponse
    Catch ex As Exception
      Dim err As String = ex.Message
      Label2.Text = err
    End Try

  End Sub

  Private Sub cmdInv_Click(sender As Object, e As EventArgs) Handles cmdInv.Click
    If rObj Is Nothing Then Exit Sub
    Dim mi As New MasterIndia
  End Sub
  Dim rObj As ClearTaxResponse = Nothing
  Private Sub cmdPost_Click(sender As Object, e As EventArgs) Handles cmdPost.Click
    L_Response.Text = ""

    Dim u As Uri = New Uri("https://clientbasic.mastersindia.co/oauth/access_token")
    Dim x As HttpWebRequest = WebRequest.Create(u)
    With x
      .Method = "POST"
      .ContentType = "application/json"
      .Accept = "*/*"
      .CachePolicy = New Cache.RequestCachePolicy(Net.Cache.RequestCacheLevel.NoCacheNoStore)
      .Headers.Add("mode", "no-cors")
      .Host = "clientbasic.mastersindia.co"
      .KeepAlive = True

    End With
    Dim jsonStr As String = New JavaScriptSerializer().Serialize(New TokenRequest)
    Dim jsonByte() As Byte = Encoding.ASCII.GetBytes(jsonStr)
    x.ContentLength = jsonByte.Count
    x.GetRequestStream().Write(jsonByte, 0, jsonByte.Count)
    Try
      Dim rs As WebResponse = x.GetResponse()
      Dim st As IO.Stream = rs.GetResponseStream
      Dim sr As IO.StreamReader = New IO.StreamReader(st)
      Dim strResponse As String = sr.ReadToEnd
      sr.Close()
      L_Response.Text = strResponse
      rObj = New JavaScriptSerializer().Deserialize(strResponse, GetType(ClearTaxResponse))
    Catch ex As Exception
      Dim err As String = ex.Message
      L_Response.Text = err
    End Try

  End Sub

  Private Sub eblDefault_Load(sender As Object, e As EventArgs) Handles Me.Load
    Dim z As String = "iVBORw0KGgoAAAANSUhEUgAAAuQAAALkCAYAAABHpCBlAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAFJDSURBVHhe7dZBjuW6ggPRv/9Nd8/eKAw4QeKaJcUBYkxB8q3K//2fJEmSpM/4B7kkSZL0If8glyRJkj7kH+SSJEnSh/yDXJIkSfqQf5BLkiRJH/IPckmSJOlD/kEuSZIkfcg/yCVJkqQP+Qe5JEmS9CH/IJckSZI+5B/kkiRJ0of8g1ySJEn6kH+QS5IkSR/yD3JJkiTpQ/5BLkmSJH3IP8glSZKkD/kHuSRJkvQh/yCXJEmSPuQf5JIkSdKH/INckiRJ+pB/kEuSJEkf8g9ySZIk6UP+QS5JkiR9yD/IJUmSpA/5B7kkSZL0If8glyRJkj7kH+SSJEnSh/yDXJIkSfqQf5BLkiRJH/IPckmSJOlD/kEuSZIkfcg/yCVJkqQP+Qe5JEmS9CH/IJckSZI+5B/kkiRJ0of8g1ySJEn6kH+QS5IkSR/yD3JJkiTpQ/5BLkmSJH3IP8glSZKkD/kHuSRJkvQh/yCXJEmSPuQf5JIkSdKH/INckiRJ+pB/kEuSJEkf8g9ySZIk6UP+QS5JkiR9yD/IJUmSpA/5B7kkSZL0If8glyRJkj7kH+SSJEnSh/yDXJIkSfqQf5BLkiRJH/IPckmSJOlD/kEuSZIkfcg/yCVJkqQP+Qe5JEmS9CH/IJckSZI+5B/kkiRJ0of8g1ySJEn6kH+QS5IkSR/yD3JJkiTpQ/5BLkmSJH3IP8glSZKkD/kHuSRJkvQh/yCXJEmSPuQf5JIkSdKH/INckiRJ+pB/kEuSJEkf8g9ySZIk6UP+QS5JkiR9yD/IJUmSpA/5B7kkSZL0If8glyRJkj7kH+SSJEnSh/yDXJIkSfqQf5BLkiRJH/IPckmSJOlD/kEuSZIkfcg/yEP/+9//zF7XRhtJt6E7SNIWeqOkNtpIaqMNs6eU8QZD9FGaPdVGG0m3oTtI0hZ6o6Q22khqow2zp5TxBkP0UZo91UYbSbehO0jSFnqjpDbaSGqjDbOnlPEGQ/RRmj3VRhtJt6E7SNIWeqOkNtpIaqMNs6eU8QZD9FGaPdVGG0m3oTtI0hZ6o6Q22khqow2zp5TxBkP0UZo91UYbSbehO0jSFnqjpDbaSGqjDbOnlPEGQ/RRmj3VRhtJt6E7SNIWeqOkNtpIaqMNs6eU8QZD9FGaPdVGG0m3oTtI0hZ6o6Q22khqow2zp5TxBkP0UZo91UYbSbehO0jSFnqjpDbaSGqjDbOnlPEGQ/RRmj3VRhtJt6E7SNIWeqOkNtpIaqMNs6eU8QZD9FGaPdVGG0m3oTtI0hZ6o6Q22khqow2zp5TxBkP0UZo91UYbSbehO0jSFnqjpDbaSGqjDbOnlPEGQ/RRmj3VRhtJt6E7SNIWeqOkNtpIaqMNs6eU8QZD9FGaPdVGG0m3oTtI0hZ6o6Q22khqow2zp5TxBkP0UZo91UYbSbehO0jSFnqjpDbaSGqjDbOnlPEGQ/RRmj3VRhtJt6E7SNIWeqOkNtpIaqMNs6eU8QZD9FGaPdVGG0m3oTtI0hZ6o6Q22khqow2zp5TxBkP0UZo91UYbSbehO0jSFnqjpDbaSGqjDbOnlPEGQ/RRmj3VRhtJt6E7SNIWeqOkNtpIaqMNs6eU8QZD9FGaPdVGG0m3oTtI0hZ6o6Q22khqow2zp5TxBkP0USZpC71R0jo681JttHFybbSR1EYbS62jMydpC71RkjLeYIg+yiRtoTdKWkdnXqqNNk6ujTaS2mhjqXV05iRtoTdKUsYbDNFHmaQt9EZJ6+jMS7XRxsm10UZSG20stY7OnKQt9EZJyniDIfook7SF3ihpHZ15qTbaOLk22khqo42l1tGZk7SF3ihJGW8wRB9lkrbQGyWtozMv1UYbJ9dGG0lttLHUOjpzkrbQGyUp4w2G6KNM0hZ6o6R1dOal2mjj5NpoI6mNNpZaR2dO0hZ6oyRlvMEQfZRJ2kJvlLSOzrxUG22cXBttJLXRxlLr6MxJ2kJvlKSMNxiijzJJW+iNktbRmZdqo42Ta6ONpDbaWGodnTlJW+iNkpTxBkP0USZpC71R0jo681JttHFybbSR1EYbS62jMydpC71RkjLeYIg+yiRtoTdKWkdnXqqNNk6ujTaS2mhjqXV05iRtoTdKUsYbDNFHmaQt9EZJ6+jMS7XRxsm10UZSG20stY7OnKQt9EZJyniDIfook7SF3ihpHZ15qTbaOLk22khqo42l1tGZk7SF3ihJGW8wRB9lkrbQGyWtozMv1UYbJ9dGG0lttLHUOjpzkrbQGyUp4w2G6KNM0hZ6o6R1dOal2mjj5NpoI6mNNpZaR2dO0hZ6oyRlvMEQfZRJ2kJvlLSOzrxUG22cXBttJLXRxlLr6MxJ2kJvlKSMNxiijzJJW+iNktbRmZdqo42Ta6ONpDbaWGodnTlJW+iNkpTxBkP0USZpC71R0jo681JttHFybbSR1EYbS62jMydpC71RkjLeYIg+yiRtoTdKWkdnXqqNNk6ujTaS2mhjqXV05iRtoTdKUsYbDNFHmaQt9EZJ6+jMS7XRxsm10UZSG20stY7OnKQt9EZJyniDIfook7SF3ihpHZ15qTbaOLk22khqo42l1tGZk7SF3ihJGW8wRB9lUhttnFwbbSStozMnraMzJ62jMyetozOfXBttJLXRxsm10UaSMt5giD7KpDbaOLk22khaR2dOWkdnTlpHZ05aR2c+uTbaSGqjjZNro40kZbzBEH2USW20cXJttJG0js6ctI7OnLSOzpy0js58cm20kdRGGyfXRhtJyniDIfook9po4+TaaCNpHZ05aR2dOWkdnTlpHZ355NpoI6mNNk6ujTaSlPEGQ/RRJrXRxsm10UbSOjpz0jo6c9I6OnPSOjrzybXRRlIbbZxcG20kKeMNhuijTGqjjZNro42kdXTmpHV05qR1dOakdXTmk2ujjaQ22ji5NtpIUsYbDNFHmdRGGyfXRhtJ6+jMSevozEnr6MxJ6+jMJ9dGG0lttHFybbSRpIw3GKKPMqmNNk6ujTaS1tGZk9bRmZPW0ZmT1tGZT66NNpLaaOPk2mgjSRlvMEQfZVIbbZxcG20kraMzJ62jMyetozMnraMzn1wbbSS10cbJtdFGkjLeYIg+yqQ22ji5NtpIWkdnTlpHZ05aR2dOWkdnPrk22khqo42Ta6ONJGW8wRB9lElttHFybbSRtI7OnLSOzpy0js6ctI7OfHJttJHURhsn10YbScp4gyH6KJPaaOPk2mgjaR2dOWkdnTlpHZ05aR2d+eTaaCOpjTZOro02kpTxBkP0USa10cbJtdFG0jo6c9I6OnPSOjpz0jo688m10UZSG22cXBttJCnjDYboo0xqo42Ta6ONpHV05qR1dOakdXTmpHV05pNro42kNto4uTbaSFLGGwzRR5nURhsn10YbSevozEnr6MxJ6+jMSevozCfXRhtJbbRxcm20kaSMNxiijzKpjTZOro02ktbRmZPW0ZmT1tGZk9bRmU+ujTaS2mjj5NpoI0kZbzBEH2VSG22cXBttJK2jMyetozMnraMzJ62jM59cG20ktdHGybXRRpIy3mCIPsqkNto4uTbaSFpHZ05aR2dOWkdnTlpHZz65NtpIaqONk2ujjSRlvMEQfZRJbbRxcm20kbSOzpy0js6ctI7OnLSOznxybbSR1EYbJ9dGG0nKeIMh+iiT2mjj5NpoI2kdnTlpHZ05aR2dOWkdnfnk2mgjqY02Tq6NNpKU8QZD9FEmtdHGybXRRpIydKdJytCdJq2jMyetozMntdHGybXRRpIy3mCIPsqkNto4uTbaSFKG7jRJGbrTpHV05qR1dOakNto4uTbaSFLGGwzRR5nURhsn10YbScrQnSYpQ3eatI7OnLSOzpzURhsn10YbScp4gyH6KJPaaOPk2mgjSRm60yRl6E6T1tGZk9bRmZPaaOPk2mgjSRlvMEQfZVIbbZxcG20kKUN3mqQM3WnSOjpz0jo6c1IbbZxcG20kKeMNhuijTGqjjZNro40kZehOk5ShO01aR2dOWkdnTmqjjZNro40kZbzBEH2USW20cXJttJGkDN1pkjJ0p0nr6MxJ6+jMSW20cXJttJGkjDcYoo8yqY02Tq6NNpKUoTtNUobuNGkdnTlpHZ05qY02Tq6NNpKU8QZD9FEmtdHGybXRRpIydKdJytCdJq2jMyetozMntdHGybXRRpIy3mCIPsqkNto4uTbaSFKG7jRJGbrTpHV05qR1dOakNto4uTbaSFLGGwzRR5nURhsn10YbScrQnSYpQ3eatI7OnLSOzpzURhsn10YbScp4gyH6KJPaaOPk2mgjSRm60yRl6E6T1tGZk9bRmZPaaOPk2mgjSRlvMEQfZVIbbZxcG20kKUN3mqQM3WnSOjpz0jo6c1IbbZxcG20kKeMNhuijTGqjjZNro40kZehOk5ShO01aR2dOWkdnTmqjjZNro40kZbzBEH2USW20cXJttJGkDN1pkjJ0p0nr6MxJ6+jMSW20cXJttJGkjDcYoo8yqY02Tq6NNpKUoTtNUobuNGkdnTlpHZ05qY02Tq6NNpKU8QZD9FEmtdHGybXRRpIydKdJytCdJq2jMyetozMntdHGybXRRpIy3mCIPsqkNto4uTbaSFKG7jRJGbrTpHV05qR1dOakNto4uTbaSFLGGwzRR5nURhsn10YbScrQnSYpQ3eatI7OnLSOzpzURhsn10YbScp4gyH6KJPaaOPk2mgjSRm60yRl6E6T1tGZk9bRmZPaaOPk2mgjSRlvMEQfZVIbbZxcG20ktdGGva+NNpZqo42kNtpYah2dOamNNk6ujTaSlPEGQ/RRJrXRxsm10UZSG23Y+9poY6k22khqo42l1tGZk9po4+TaaCNJGW8wRB9lUhttnFwbbSS10Ya9r402lmqjjaQ22lhqHZ05qY02Tq6NNpKU8QZD9FEmtdHGybXRRlIbbdj72mhjqTbaSGqjjaXW0ZmT2mjj5NpoI0kZbzBEH2VSG22cXBttJLXRhr2vjTaWaqONpDbaWGodnTmpjTZOro02kpTxBkP0USa10cbJtdFGUhtt2PvaaGOpNtpIaqONpdbRmZPaaOPk2mgjSRlvMEQfZVIbbZxcG20ktdGGva+NNpZqo42kNtpYah2dOamNNk6ujTaSlPEGQ/RRJrXRxsm10UZSG23Y+9poY6k22khqo42l1tGZk9po4+TaaCNJGW8wRB9lUhttnFwbbSS10Ya9r402lmqjjaQ22lhqHZ05qY02Tq6NNpKU8QZD9FEmtdHGybXRRlIbbdj72mhjqTbaSGqjjaXW0ZmT2mjj5NpoI0kZbzBEH2VSG22cXBttJLXRhr2vjTaWaqONpDbaWGodnTmpjTZOro02kpTxBkP0USa10cbJtdFGUhtt2PvaaGOpNtpIaqONpdbRmZPaaOPk2mgjSRlvMEQfZVIbbZxcG20ktdGGva+NNpZqo42kNtpYah2dOamNNk6ujTaSlPEGQ/RRJrXRxsm10UZSG23Y+9poY6k22khqo42l1tGZk9po4+TaaCNJGW8wRB9lUhttnFwbbSS10Ya9r402lmqjjaQ22lhqHZ05qY02Tq6NNpKU8QZD9FEmtdHGybXRRlIbbdj72mhjqTbaSGqjjaXW0ZmT2mjj5NpoI0kZbzBEH2VSG22cXBttJLXRhr2vjTaWaqONpDbaWGodnTmpjTZOro02kpTxBkP0USa10cbJtdFGUhtt2PvaaGOpNtpIaqONpdbRmZPaaOPk2mgjSRlvMEQfZVIbbZxcG20ktdGGva+NNpZqo42kNtpYah2dOamNNk6ujTaSlPEGQ/RRJrXRxsm10UZSG23Y+9poY6k22khqo42l1tGZk9po4+TaaCNJGW8wRB9lkrbQGyW10YbZr1pHZ05qo42kNtpI0hZ6oyRlvMEQfZRJ2kJvlNRGG2a/ah2dOamNNpLaaCNJW+iNkpTxBkP0USZpC71RUhttmP2qdXTmpDbaSGqjjSRtoTdKUsYbDNFHmaQt9EZJbbRh9qvW0ZmT2mgjqY02krSF3ihJGW8wRB9lkrbQGyW10YbZr1pHZ05qo42kNtpI0hZ6oyRlvMEQfZRJ2kJvlNRGG2a/ah2dOamNNpLaaCNJW+iNkpTxBkP0USZpC71RUhttmP2qdXTmpDbaSGqjjSRtoTdKUsYbDNFHmaQt9EZJbbRh9qvW0ZmT2mgjqY02krSF3ihJGW8wRB9lkrbQGyW10YbZr1pHZ05qo42kNtpI0hZ6oyRlvMEQfZRJ2kJvlNRGG2a/ah2dOamNNpLaaCNJW+iNkpTxBkP0USZpC71RUhttmP2qdXTmpDbaSGqjjSRtoTdKUsYbDNFHmaQt9EZJbbRh9qvW0ZmT2mgjqY02krSF3ihJGW8wRB9lkrbQGyW10YbZr1pHZ05qo42kNtpI0hZ6oyRlvMEQfZRJ2kJvlNRGG2a/ah2dOamNNpLaaCNJW+iNkpTxBkP0USZpC71RUhttmP2qdXTmpDbaSGqjjSRtoTdKUsYbDNFHmaQt9EZJbbRh9qvW0ZmT2mgjqY02krSF3ihJGW8wRB9lkrbQGyW10YbZr1pHZ05qo42kNtpI0hZ6oyRlvMEQfZRJ2kJvlNRGG2a/ah2dOamNNpLaaCNJW+iNkpTxBkP0USZpC71RUhttmP2qdXTmpDbaSGqjjSRtoTdKUsYbDNFHmaQt9EZJbbRh9qvW0ZmT2mgjqY02krSF3ihJGW8wRB+l2VNttJHURhtJbbSR1EYbSW20kdRGG0lttJHURhtmTynjDYboozR7qo02ktpoI6mNNpLaaCOpjTaS2mgjqY02ktpow+wpZbzBEH2UZk+10UZSG20ktdFGUhttJLXRRlIbbSS10UZSG22YPaWMNxiij9LsqTbaSGqjjaQ22khqo42kNtpIaqONpDbaSGqjDbOnlPEGQ/RRmj3VRhtJbbSR1EYbSW20kdRGG0lttJHURhtJbbRh9pQy3mCIPkqzp9poI6mNNpLaaCOpjTaS2mgjqY02ktpoI6mNNsyeUsYbDNFHafZUG20ktdFGUhttJLXRRlIbbSS10UZSG20ktdGG2VPKeIMh+ijNnmqjjaQ22khqo42kNtpIaqONpDbaSGqjjaQ22jB7ShlvMEQfpdlTbbSR1EYbSW20kdRGG0lttJHURhtJbbSR1EYbZk8p4w2G6KM0e6qNNpLaaCOpjTaS2mgjqY02ktpoI6mNNpLaaMPsKWW8wRB9lGZPtdFGUhttJLXRRlIbbSS10UZSG20ktdFGUhttmD2ljDcYoo/S7Kk22khqo42kNtpIaqONpDbaSGqjjaQ22khqow2zp5TxBkP0UZo91UYbSW20kdRGG0lttJHURhtJbbSR1EYbSW20YfaUMt5giD5Ks6faaCOpjTaS2mgjqY02ktpoI6mNNpLaaCOpjTbMnlLGGwzRR2n2VBttJLXRRlIbbSS10UZSG20ktdFGUhttJLXRhtlTyniDIfoozZ5qo42kNtpIaqONpDbaSGqjjaQ22khqo42kNtowe0oZbzBEH6XZU220kdRGG0lttJHURhtJbbSR1EYbSW20kdRGG2ZPKeMNhuijNHuqjTaS2mgjqY02ktpoI6mNNpLaaCOpjTaS2mjD7CllvMEQfZRmT7XRRlIbbSS10UZSG20ktdFGUhttJLXRRlIbbZg9pYw3GKKP0uypNtpIaqONpDbaSGqjjaQ22khqo42kNtpIaqMNs6eU8QYl/Yf+kU1aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oIl/Yf+k09aR2deah2dOek2dAdJkv5d/oLH0D+yZk+10cZSbbSRpC30Rie3js681G3oDpKU8QbH0Edu9lQbbSzVRhtJ2kJvdHLr6MxL3YbuIEkZb3AMfeRmT7XRxlJttJGkLfRGJ7eOzrzUbegOkpTxBsfQR272VBttLNVGG0naQm90cuvozEvdhu4gSRlvcAx95GZPtdHGUm20kaQt9EYnt47OvNRt6A6SlPEGx9BHbvZUG20s1UYbSdpCb3Ry6+jMS92G7iBJGW9wDH3kZk+10cZSbbSRpC30Rie3js681G3oDpKU8QbH0Edu9lQbbSzVRhtJ2kJvdHLr6MxL3YbuIEkZb3AMfeRmT7XRxlJttJGkLfRGJ7eOzrzUbegOkpTxBsfQR272VBttLNVGG0naQm90cuvozEvdhu4gSRlvcAx95GZPtdHGUm20kaQt9EYnt47OvNRt6A6SlPEGx9BHbvZUG20s1UYbSdpCb3Ry6+jMS92G7iBJGW9wDH3kZk+10cZSbbSRpC30Rie3js681G3oDpKU8QbH0Edu9lQbbSzVRhtJ2kJvdHLr6MxL3YbuIEkZb3AMfeRmT7XRxlJttJGkLfRGJ7eOzrzUbegOkpTxBsfQR272VBttLNVGG0naQm90cuvozEvdhu4gSRlvcAx95GZPtdHGUm20kaQt9EYnt47OvNRt6A6SlPEGx9BHbvZUG20s1UYbSdpCb3Ry6+jMS92G7iBJGW9wDH3kZk+10cZSbbSRpC30Rie3js681G3oDpKU8QbH0Edu9lQbbSzVRhtJ2kJvdHLr6MxL3YbuIEkZb/Bw9KOx97XRhr2vjTZOro02lroN3UHSOjrzUm20sZQy3uDh6Edj72ujDXtfG22cXBttLHUbuoOkdXTmpdpoYyllvMHD0Y/G3tdGG/a+Nto4uTbaWOo2dAdJ6+jMS7XRxlLKeIOHox+Nva+NNux9bbRxcm20sdRt6A6S1tGZl2qjjaWU8QYPRz8ae18bbdj72mjj5NpoY6nb0B0kraMzL9VGG0sp4w0ejn409r422rD3tdHGybXRxlK3oTtIWkdnXqqNNpZSxhs8HP1o7H1ttGHva6ONk2ujjaVuQ3eQtI7OvFQbbSyljDd4OPrR2PvaaMPe10YbJ9dGG0vdhu4gaR2deak22lhKGW/wcPSjsfe10Ya9r402Tq6NNpa6Dd1B0jo681JttLGUMt7g4ehHY+9row17XxttnFwbbSx1G7qDpHV05qXaaGMpZbzBw9GPxt7XRhv2vjbaOLk22ljqNnQHSevozEu10cZSyniDh6Mfjb2vjTbsfW20cXJttLHUbegOktbRmZdqo42llPEGD0c/GntfG23Y+9po4+TaaGOp29AdJK2jMy/VRhtLKeMNHo5+NPa+Ntqw97XRxsm10cZSt6E7SFpHZ16qjTaWUsYbPBz9aOx9bbRh72ujjZNro42lbkN3kLSOzrxUG20spYw3eDj60dj72mjD3tdGGyfXRhtL3YbuIGkdnXmpNtpYShlv8HD0o7H3tdGGva+NNk6ujTaWug3dQdI6OvNSbbSxlDLe4OHoR2Pva6MNe18bbZxcG20sdRu6g6R1dOal2mhjKWW8wcPRj8be10Yb9r422ji5NtpY6jZ0B0nr6MxLtdHGUsp4g4ejH429r4027H1ttHFybbSx1G3oDpLW0ZmXaqONpZTxBkP0US6lDN2p2a9qo40kZehOl2qjDXufzuYLh+hHs5QydKdmv6qNNpKUoTtdqo027H06my8coh/NUsrQnZr9qjbaSFKG7nSpNtqw9+lsvnCIfjRLKUN3avar2mgjSRm606XaaMPep7P5wiH60SylDN2p2a9qo40kZehOl2qjDXufzuYLh+hHs5QydKdmv6qNNpKUoTtdqo027H06my8coh/NUsrQnZr9qjbaSFKG7nSpNtqw9+lsvnCIfjRLKUN3avar2mgjSRm606XaaMPep7P5wiH60SylDN2p2a9qo40kZehOl2qjDXufzuYLh+hHs5QydKdmv6qNNpKUoTtdqo027H06my8coh/NUsrQnZr9qjbaSFKG7nSpNtqw9+lsvnCIfjRLKUN3avar2mgjSRm606XaaMPep7P5wiH60SylDN2p2a9qo40kZehOl2qjDXufzuYLh+hHs5QydKdmv6qNNpKUoTtdqo027H06my8coh/NUsrQnZr9qjbaSFKG7nSpNtqw9+lsvnCIfjRLKUN3avar2mgjSRm606XaaMPep7P5wiH60SylDN2p2a9qo40kZehOl2qjDXufzuYLh+hHs5QydKdmv6qNNpKUoTtdqo027H06my8coh/NUsrQnZr9qjbaSFKG7nSpNtqw9+lsvnCIfjRLKUN3avar2mgjSRm606XaaMPep7P5wiH60dg5KUN3mtRGG0m3oTtIaqONpHV05qR1dOal2mgjSVt8kRB95HZOytCdJrXRRtJt6A6S2mgjaR2dOWkdnXmpNtpI0hZfJEQfuZ2TMnSnSW20kXQbuoOkNtpIWkdnTlpHZ16qjTaStMUXCdFHbuekDN1pUhttJN2G7iCpjTaS1tGZk9bRmZdqo40kbfFFQvSR2zkpQ3ea1EYbSbehO0hqo42kdXTmpHV05qXaaCNJW3yREH3kdk7K0J0mtdFG0m3oDpLaaCNpHZ05aR2deak22kjSFl8kRB+5nZMydKdJbbSRdBu6g6Q22khaR2dOWkdnXqqNNpK0xRcJ0Udu56QM3WlSG20k3YbuIKmNNpLW0ZmT1tGZl2qjjSRt8UVC9JHbOSlDd5rURhtJt6E7SGqjjaR1dOakdXTmpdpoI0lbfJEQfeR2TsrQnSa10UbSbegOktpoI2kdnTlpHZ15qTbaSNIWXyREH7mdkzJ0p0lttJF0G7qDpDbaSFpHZ05aR2deqo02krTFFwnRR27npAzdaVIbbSTdhu4gqY02ktbRmZPW0ZmXaqONJG3xRUL0kds5KUN3mtRGG0m3oTtIaqONpHV05qR1dOal2mgjSVt8kRB95HZOytCdJrXRRtJt6A6S2mgjaR2dOWkdnXmpNtpI0hZfJEQfuZ2TMnSnSW20kXQbuoOkNtpIWkdnTlpHZ16qjTaStMUXCdFHbuekDN1pUhttJN2G7iCpjTaS1tGZk9bRmZdqo40kbfFFQvSR2zkpQ3ea1EYbSbehO0hqo42kdXTmpHV05qXaaCNJW3yREH3kdk7K0J0mtdFG0m3oDpLaaCNpHZ05aR2deak22kjSFl8kRB+5nZMydKdJbbSRdBu6g6Q22khaR2dOWkdnXqqNNpK0xRcJ0Udu56QM3WlSG20k3YbuIKmNNpLW0ZmT1tGZl2qjjSRt8UVC9JEvpQzd6VK3oTtIWkdntvdJf0HfkL1PGW8wRB/lUsrQnS51G7qDpHV0Znuf9Bf0Ddn7lPEGQ/RRLqUM3elSt6E7SFpHZ7b3SX9B35C9TxlvMEQf5VLK0J0udRu6g6R1dGZ7n/QX9A3Z+5TxBkP0US6lDN3pUrehO0haR2e290l/Qd+QvU8ZbzBEH+VSytCdLnUbuoOkdXRme5/0F/QN2fuU8QZD9FEupQzd6VK3oTtIWkdntvdJf0HfkL1PGW8wRB/lUsrQnS51G7qDpHV0Znuf9Bf0Ddn7lPEGQ/RRLqUM3elSt6E7SFpHZ7b3SX9B35C9TxlvMEQf5VLK0J0udRu6g6R1dGZ7n/QX9A3Z+5TxBkP0US6lDN3pUrehO0haR2e290l/Qd+QvU8ZbzBEH+VSytCdLnUbuoOkdXRme5/0F/QN2fuU8QZD9FEupQzd6VK3oTtIWkdntvdJf0HfkL1PGW8wRB/lUsrQnS51G7qDpHV0Znuf9Bf0Ddn7lPEGQ/RRLqUM3elSt6E7SFpHZ7b3SX9B35C9TxlvMEQf5VLK0J0udRu6g6R1dGZ7n/QX9A3Z+5TxBkP0US6lDN3pUrehO0haR2e290l/Qd+QvU8ZbzBEH+VSytCdLnUbuoOkdXRme5/0F/QN2fuU8QZD9FEupQzd6VK3oTtIWkdntvdJf0HfkL1PGW8wRB/lUsrQnS51G7qDpHV0Znuf9Bf0Ddn7lPEGQ/RRLtVGG0vdhu4gqY02ktbRmZNuQ3dg37WOzrxUG20kaYsvEqKPfKk22ljqNnQHSW20kbSOzpx0G7oD+651dOal2mgjSVt8kRB95Eu10cZSt6E7SGqjjaR1dOak29Ad2HetozMv1UYbSdrii4ToI1+qjTaWug3dQVIbbSStozMn3YbuwL5rHZ15qTbaSNIWXyREH/lSbbSx1G3oDpLaaCNpHZ056TZ0B/Zd6+jMS7XRRpK2+CIh+siXaqONpW5Dd5DURhtJ6+jMSbehO7DvWkdnXqqNNpK0xRcJ0Ue+VBttLHUbuoOkNtpIWkdnTroN3YF91zo681JttJGkLb5IiD7ypdpoY6nb0B0ktdFG0jo6c9Jt6A7su9bRmZdqo40kbfFFQvSRL9VGG0vdhu4gqY02ktbRmZNuQ3dg37WOzrxUG20kaYsvEqKPfKk22ljqNnQHSW20kbSOzpx0G7oD+651dOal2mgjSVt8kRB95Eu10cZSt6E7SGqjjaR1dOak29Ad2HetozMv1UYbSdrii4ToI1+qjTaWug3dQVIbbSStozMn3YbuwL5rHZ15qTbaSNIWXyREH/lSbbSx1G3oDpLaaCNpHZ056TZ0B/Zd6+jMS7XRRpK2+CIh+siXaqONpW5Dd5DURhtJ6+jMSbehO7DvWkdnXqqNNpK0xRcJ0Ue+VBttLHUbuoOkNtpIWkdnTroN3YF91zo681JttJGkLb5IiD7ypdpoY6nb0B0ktdFG0jo6c9Jt6A7su9bRmZdqo40kbfFFQvSRL9VGG0vdhu4gqY02ktbRmZNuQ3dg37WOzrxUG20kaYsvEqKPfKk22ljqNnQHSW20kbSOzpx0G7oD+651dOal2mgjSVt8kRB95Eu10cZSt6E7SGqjjaR1dOak29Ad2HetozMv1UYbSdrii4ToI1+qjTaWug3dQVIbbSStozMn3YbuwL5rHZ15qTbaSNIWX+Rw9CNMug3dwcmtozMnraMz2/vW0ZmT2mhjqTbaSJL+wi/mcPSPRNJt6A5Obh2dOWkdndnet47OnNRGG0u10UaS9Bd+MYejfySSbkN3cHLr6MxJ6+jM9r51dOakNtpYqo02kqS/8Is5HP0jkXQbuoOTW0dnTlpHZ7b3raMzJ7XRxlJttJEk/YVfzOHoH4mk29AdnNw6OnPSOjqzvW8dnTmpjTaWaqONJOkv/GIOR/9IJN2G7uDk1tGZk9bRme196+jMSW20sVQbbSRJf+EXczj6RyLpNnQHJ7eOzpy0js5s71tHZ05qo42l2mgjSfoLv5jD0T8SSbehOzi5dXTmpHV0ZnvfOjpzUhttLNVGG0nSX/jFHI7+kUi6Dd3Bya2jMyetozPb+9bRmZPaaGOpNtpIkv7CL+Zw9I9E0m3oDk5uHZ05aR2d2d63js6c1EYbS7XRRpL0F34xh6N/JJJuQ3dwcuvozEnr6Mz2vnV05qQ22liqjTaSpL/wizkc/SORdBu6g5NbR2dOWkdntvetozMntdHGUm20kST9hV/M4egfiaTb0B2c3Do6c9I6OrO9bx2dOamNNpZqo40k6S/8Yg5H/0gk3Ybu4OTW0ZmT1tGZ7X3r6MxJbbSxVBttJEl/4RdzOPpHIuk2dAcnt47OnLSOzmzvW0dnTmqjjaXaaCNJ+gu/mMPRPxJJt6E7OLl1dOakdXRme986OnNSG20s1UYbSdJf+MUcjv6RSLoN3cHJraMzJ62jM9v71tGZk9poY6k22kiS/sIv5nD0j0TSbegOTm4dnTlpHZ3Z3reOzpzURhtLtdFGkvQXfjGHo38kkm5Dd3By6+jMSevozPa+dXTmpDbaWKqNNpKkv/CLORz9I5F0G7qDk1tHZ05aR2e2962jMye10cZSbbSRJP2FX0yIfoRJbbRxcuvozElttJG0js681G3oDpZaR2c+uTbaSGqjjSRt8UVC9JEntdHGya2jMye10UbSOjrzUrehO1hqHZ355NpoI6mNNpK0xRcJ0Uee1EYbJ7eOzpzURhtJ6+jMS92G7mCpdXTmk2ujjaQ22kjSFl8kRB95UhttnNw6OnNSG20kraMzL3UbuoOl1tGZT66NNpLaaCNJW3yREH3kSW20cXLr6MxJbbSRtI7OvNRt6A6WWkdnPrk22khqo40kbfFFQvSRJ7XRxsmtozMntdFG0jo681K3oTtYah2d+eTaaCOpjTaStMUXCdFHntRGGye3js6c1EYbSevozEvdhu5gqXV05pNro42kNtpI0hZfJEQfeVIbbZzcOjpzUhttJK2jMy91G7qDpdbRmU+ujTaS2mgjSVt8kRB95ElttHFy6+jMSW20kbSOzrzUbegOllpHZz65NtpIaqONJG3xRUL0kSe10cbJraMzJ7XRRtI6OvNSt6E7WGodnfnk2mgjqY02krTFFwnRR57URhsnt47OnNRGG0nr6MxL3YbuYKl1dOaTa6ONpDbaSNIWXyREH3lSG22c3Do6c1IbbSStozMvdRu6g6XW0ZlPro02ktpoI0lbfJEQfeRJbbRxcuvozElttJG0js681G3oDpZaR2c+uTbaSGqjjSRt8UVC9JEntdHGya2jMye10UbSOjrzUrehO1hqHZ355NpoI6mNNpK0xRcJ0Uee1EYbJ7eOzpzURhtJ6+jMS92G7mCpdXTmk2ujjaQ22kjSFl8kRB95UhttnNw6OnNSG20kraMzL3UbuoOl1tGZT66NNpLaaCNJW3yREH3kSW20cXLr6MxJbbSRtI7OvNRt6A6WWkdnPrk22khqo40kbfFFQvSRJ7XRxsmtozMntdFG0jo681K3oTtYah2d+eTaaCOpjTaStMUXCdFHntRGGye3js6c1EYbSevozEvdhu5gqXV05pNro42kNtpI0hZfJEQfeVIbbZzcOjpzUhttJK2jMy91G7qDpdbRmU+ujTaS2mgjSVt8kRB95PZdbbSRtI7OvFQbbSS10cbJaQu9UdJt6A6W0hZfJEQfuX1XG20kraMzL9VGG0lttHFy2kJvlHQbuoOltMUXCdFHbt/VRhtJ6+jMS7XRRlIbbZycttAbJd2G7mApbfFFQvSR23e10UbSOjrzUm20kdRGGyenLfRGSbehO1hKW3yREH3k9l1ttJG0js68VBttJLXRxslpC71R0m3oDpbSFl8kRB+5fVcbbSStozMv1UYbSW20cXLaQm+UdBu6g6W0xRcJ0Udu39VGG0nr6MxLtdFGUhttnJy20Bsl3YbuYClt8UVC9JHbd7XRRtI6OvNSbbSR1EYbJ6ct9EZJt6E7WEpbfJEQfeT2XW20kbSOzrxUG20ktdHGyWkLvVHSbegOltIWXyREH7l9VxttJK2jMy/VRhtJbbRxctpCb5R0G7qDpbTFFwnRR27f1UYbSevozEu10UZSG22cnLbQGyXdhu5gKW3xRUL0kdt3tdFG0jo681JttJHURhsnpy30Rkm3oTtYSlt8kRB95PZdbbSRtI7OvFQbbSS10cbJaQu9UdJt6A6W0hZfJEQfuX1XG20kraMzL9VGG0lttHFy2kJvlHQbuoOltMUXCdFHbt/VRhtJ6+jMS7XRRlIbbZycttAbJd2G7mApbfFFQvSR23e10UbSOjrzUm20kdRGGyenLfRGSbehO1hKW3yREH3k9l1ttJG0js68VBttJLXRxslpC71R0m3oDpbSFl8kRB+5fVcbbSStozMv1UYbSW20cXLaQm+UdBu6g6W0xRcJ0Udu39VGG0nr6MxLtdFGUhttnJy20Bsl3YbuYClt8UVC9JHbd7XRRtI6OvNSbbSR1EYbJ6ct9EZJt6E7WEpbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbSevozEnr6MxJbbRh71tHZ05qo42l2mjj5NpoI0lbfJEQfeRJbbSR1EYbZnZnbbSxVBttLNVGG0tJf+EXE6IfYVIbbSS10YaZ3VkbbSzVRhtLtdHGUtJf+MWE6EeY1EYbSW20YWZ31kYbS7XRxlJttLGU9Bd+MSH6ESa10UZSG22Y2Z210cZSbbSxVBttLCX9hV9MiH6ESW20kdRGG2Z2Z220sVQbbSzVRhtLSX/hFxOiH2FSG20ktdGGmd1ZG20s1UYbS7XRxlLSX/jFhOhHmNRGG0lttGFmd9ZGG0u10cZSbbSxlPQXfjEh+hEmtdFGUhttmNmdtdHGUm20sVQbbSwl/YVfTIh+hElttJHURhtmdmdttLFUG20s1UYbS0l/4RcToh9hUhttJLXRhpndWRttLNVGG0u10cZS0l/4xYToR5jURhtJbbRhZnfWRhtLtdHGUm20sZT0F34xIfoRJrXRRlIbbZjZnbXRxlJttLFUG20sJf2FX0yIfoRJbbSR1EYbZnZnbbSxVBttLNVGG0tJf+EXE6IfYVIbbSS10YaZ3VkbbSzVRhtLtdHGUtJf+MWE6EeY1EYbSW20YWZ31kYbS7XRxlJttLGU9Bd+MSH6ESa10UZSG22Y2Z210cZSbbSxVBttLCX9hV9MiH6ESW20kdRGG2Z2Z220sVQbbSzVRhtLSX/hFxOiH2FSG20ktdGGmd1ZG20s1UYbS7XRxlLSX/jFhOhHmNRGG0lttGFmd9ZGG0u10cZSbbSxlPQXfjEh+hEmtdFGUhttmNmdtdHGUm20sVQbbSwl/YVfTIh+hEnr6MxJbbSRdBu6g6Q22khaR2de6jZ0B0utozOfXBttLKWMNxiijzJpHZ05qY02km5Dd5DURhtJ6+jMS92G7mCpdXTmk2ujjaWU8QZD9FEmraMzJ7XRRtJt6A6S2mgjaR2deanb0B0stY7OfHJttLGUMt5giD7KpHV05qQ22ki6Dd1BUhttJK2jMy91G7qDpdbRmU+ujTaWUsYbDNFHmbSOzpzURhtJt6E7SGqjjaR1dOalbkN3sNQ6OvPJtdHGUsp4gyH6KJPW0ZmT2mgj6TZ0B0lttJG0js681G3oDpZaR2c+uTbaWEoZbzBEH2XSOjpzUhttJN2G7iCpjTaS1tGZl7oN3cFS6+jMJ9dGG0sp4w2G6KNMWkdnTmqjjaTb0B0ktdFG0jo681K3oTtYah2d+eTaaGMpZbzBEH2USevozElttJF0G7qDpDbaSFpHZ17qNnQHS62jM59cG20spYw3GKKPMmkdnTmpjTaSbkN3kNRGG0nr6MxL3YbuYKl1dOaTa6ONpZTxBkP0USatozMntdFG0m3oDpLaaCNpHZ15qdvQHSy1js58cm20sZQy3mCIPsqkdXTmpDbaSLoN3UFSG20kraMzL3UbuoOl1tGZT66NNpZSxhsM0UeZtI7OnNRGG0m3oTtIaqONpHV05qVuQ3ew1Do688m10cZSyniDIfook9bRmZPaaCPpNnQHSW20kbSOzrzUbegOllpHZz65NtpYShlvMEQfZdI6OnNSG20k3YbuIKmNNpLW0ZmXug3dwVLr6Mwn10YbSynjDYboo0xaR2dOaqONpNvQHSS10UbSOjrzUrehO1hqHZ355NpoYyllvMEQfZRJ6+jMSW20kXQbuoOkNtpIWkdnXuo2dAdLraMzn1wbbSyljDcYoo8yaR2dOamNNpJuQ3eQ1EYbSevozEvdhu5gqXV05pNro42llPEGQ/RRJq2jMye10UbSbegOktpoI2kdnXmp29AdLLWOznxybbSxlDLeYIg+yqR1dOakNtpIug3dQVIbbSStozMvdRu6g6XW0ZlPro02llLGGwzRR5nURhtLtdGGfddt6A7su9pow+xX6Wy+cIh+NElttLFUG23Yd92G7sC+q402zH6VzuYLh+hHk9RGG0u10YZ9123oDuy72mjD7FfpbL5wiH40SW20sVQbbdh33YbuwL6rjTbMfpXO5guH6EeT1EYbS7XRhn3XbegO7LvaaMPsV+lsvnCIfjRJbbSxVBtt2Hfdhu7AvquNNsx+lc7mC4foR5PURhtLtdGGfddt6A7su9pow+xX6Wy+cIh+NElttLFUG23Yd92G7sC+q402zH6VzuYLh+hHk9RGG0u10YZ9123oDuy72mjD7FfpbL5wiH40SW20sVQbbdh33YbuwL6rjTbMfpXO5guH6EeT1EYbS7XRhn3XbegO7LvaaMPsV+lsvnCIfjRJbbSxVBtt2Hfdhu7AvquNNsx+lc7mC4foR5PURhtLtdGGfddt6A7su9pow+xX6Wy+cIh+NElttLFUG23Yd92G7sC+q402zH6VzuYLh+hHk9RGG0u10YZ9123oDuy72mjD7FfpbL5wiH40SW20sVQbbdh33YbuwL6rjTbMfpXO5guH6EeT1EYbS7XRhn3XbegO7LvaaMPsV+lsvnCIfjRJbbSxVBtt2Hfdhu7AvquNNsx+lc7mC4foR5PURhtLtdGGfddt6A7su9pow+xX6Wy+cIh+NElttLFUG23Yd92G7sC+q402zH6VzuYLS/8w+kd7qTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNSv8w+kdxqTbaSGqjjaR1dOakNtpIaqONpNvQHdh3KeMNhuijNHuqjTaS2mjD7Kk22ji5NtpIaqONpHV05iRt8UVC9JGbPdVGG0lttGH2VBttnFwbbSS10UbSOjpzkrb4IiH6yM2eaqONpDbaMHuqjTZOro02ktpoI2kdnTlJW3yREH3kZk+10UZSG22YPdVGGyfXRhtJbbSRtI7OnKQtvkiIPnKzp9poI6mNNsyeaqONk2ujjaQ22khaR2dO0hZfJEQfudlTbbSR1EYbZk+10cbJtdFGUhttJK2jMydpiy8Soo/c7Kk22khqow2zp9po4+TaaCOpjTaS1tGZk7TFFwnRR272VBttJLXRhtlTbbRxcm20kdRGG0nr6MxJ2uKLhOgjN3uqjTaS2mjD7Kk22ji5NtpIaqONpHV05iRt8UVC9JGbPdVGG0lttGH2VBttnFwbbSS10UbSOjpzkrb4IiH6yM2eaqONpDbaMHuqjTZOro02ktpoI2kdnTlJW3yREH3kZk+10UZSG22YPdVGGyfXRhtJbbSRtI7OnKQtvkiIPnKzp9poI6mNNsyeaqONk2ujjaQ22khaR2dO0hZfJEQfudlTbbSR1EYbZk+10cbJtdFGUhttJK2jMydpiy8Soo/c7Kk22khqow2zp9po4+TaaCOpjTaS1tGZk7TFFwnRR272VBttJLXRhtlTbbRxcm20kdRGG0nr6MxJ2uKLhOgjN3uqjTaS2mjD7Kk22ji5NtpIaqONpHV05iRt8UVC9JGbPdVGG0lttGH2VBttnFwbbSS10UbSOjpzkrb4IiH6yM2eaqONpDbaMHuqjTZOro02ktpoI2kdnTlJW3yREH3kZk+10UZSG22YPdVGGyfXRhtJbbSRtI7OnKQtvkiIPvIkbaE3SmqjjaR1dOak29AdJN2G7mCp29AdLNVGG0na4ouE6CNP0hZ6o6Q22khaR2dOug3dQdJt6A6Wug3dwVJttJGkLb5IiD7yJG2hN0pqo42kdXTmpNvQHSTdhu5gqdvQHSzVRhtJ2uKLhOgjT9IWeqOkNtpIWkdnTroN3UHSbegOlroN3cFSbbSRpC2+SIg+8iRtoTdKaqONpHV05qTb0B0k3YbuYKnb0B0s1UYbSdrii4ToI0/SFnqjpDbaSFpHZ066Dd1B0m3oDpa6Dd3BUm20kaQtvkiIPvIkbaE3SmqjjaR1dOak29AdJN2G7mCp29AdLNVGG0na4ouE6CNP0hZ6o6Q22khaR2dOug3dQdJt6A6Wug3dwVJttJGkLb5IiD7yJG2hN0pqo42kdXTmpNvQHSTdhu5gqdvQHSzVRhtJ2uKLhOgjT9IWeqOkNtpIWkdnTroN3UHSbegOlroN3cFSbbSRpC2+SIg+8iRtoTdKaqONpHV05qTb0B0k3YbuYKnb0B0s1UYbSdrii4ToI0/SFnqjpDbaSFpHZ066Dd1B0m3oDpa6Dd3BUm20kaQtvkiIPvIkbaE3SmqjjaR1dOak29AdJN2G7mCp29AdLNVGG0na4ouE6CNP0hZ6o6Q22khaR2dOug3dQdJt6A6Wug3dwVJttJGkLb5IiD7yJG2hN0pqo42kdXTmpNvQHSTdhu5gqdvQHSzVRhtJ2uKLhOgjT9IWeqOkNtpIWkdnTroN3UHSbegOlroN3cFSbbSRpC2+SIg+8iRtoTdKaqONpHV05qTb0B0k3YbuYKnb0B0s1UYbSdrii4ToI0/SFnqjpDbaSFpHZ066Dd1B0m3oDpa6Dd3BUm20kaQtvkiIPvIkbaE3SmqjjaR1dOak29AdJN2G7mCp29AdLNVGG0na4ouE6CNP0hZ6o6Q22khaR2dOug3dQdJt6A6Wug3dwVJttJGkLb5IiD7ypDbaOLk22khqo42kdXTmpDbaSFKG7jSpjTbsu9poI0ln84VD9KNJaqONk2ujjaQ22khaR2dOaqONJGXoTpPaaMO+q402knQ2XzhEP5qkNto4uTbaSGqjjaR1dOakNtpIUobuNKmNNuy72mgjSWfzhUP0o0lqo42Ta6ONpDbaSFpHZ05qo40kZehOk9pow76rjTaSdDZfOEQ/mqQ22ji5NtpIaqONpHV05qQ22khShu40qY027LvaaCNJZ/OFQ/SjSWqjjZNro42kNtpIWkdnTmqjjSRl6E6T2mjDvquNNpJ0Nl84RD+apDbaOLk22khqo42kdXTmpDbaSFKG7jSpjTbsu9poI0ln84VD9KNJaqONk2ujjaQ22khaR2dOaqONJGXoTpPaaMO+q402knQ2XzhEP5qkNto4uTbaSGqjjaR1dOakNtpIUobuNKmNNuy72mgjSWfzhUP0o0lqo42Ta6ONpDbaSFpHZ05qo40kZehOk9pow76rjTaSdDZfOEQ/mqQ22ji5NtpIaqONpHV05qQ22khShu40qY027LvaaCNJZ/OFQ/SjSWqjjZNro42kNtpIWkdnTmqjjSRl6E6T2mjDvquNNpJ0Nl84RD+apDbaOLk22khqo42kdXTmpDbaSFKG7jSpjTbsu9poI0ln84VD9KNJaqONk2ujjaQ22khaR2dOaqONJGXoTpPaaMO+q402knQ2XzhEP5qkNto4uTbaSGqjjaR1dOakNtpIUobuNKmNNuy72mgjSWfzhUP0o0lqo42Ta6ONpDbaSFpHZ05qo40kZehOk9pow76rjTaSdDZfOEQ/mqQ22ji5NtpIaqONpHV05qQ22khShu40qY027LvaaCNJZ/OFQ/SjSWqjjZNro42kNtpIWkdnTmqjjSRl6E6T2mjDvquNNpJ0Nl84RD+apDbaOLk22khqo42kdXTmpDbaSFKG7jSpjTbsu9poI0ln84VD9KNJaqONk2ujjaQ22khaR2dOaqONJGXoTpPaaMO+q402knQ2XzhEP5qkNto4uTbaSGqjjaVuQ3eQ1EYbJ3cbuoMkSb/jLy5E/4gltdHGybXRRlIbbSx1G7qDpDbaOLnb0B0kSfodf3Eh+kcsqY02Tq6NNpLaaGOp29AdJLXRxsndhu4gSdLv+IsL0T9iSW20cXJttJHURhtL3YbuIKmNNk7uNnQHSZJ+x19ciP4RS2qjjZNro42kNtpY6jZ0B0lttHFyt6E7SJL0O/7iQvSPWFIbbZxcG20ktdHGUrehO0hqo42Tuw3dQZKk3/EXF6J/xJLaaOPk2mgjqY02lroN3UFSG22c3G3oDpIk/Y6/uBD9I5bURhsn10YbSW20sdRt6A6S2mjj5G5Dd5Ak6Xf8xYXoH7GkNto4uTbaSGqjjaVuQ3eQ1EYbJ3cbuoMkSb/jLy5E/4gltdHGybXRRlIbbSx1G7qDpDbaOLnb0B0kSfodf3Eh+kcsqY02Tq6NNpLaaGOp29AdJLXRxsndhu4gSdLv+IsL0T9iSW20cXJttJHURhtL3YbuIKmNNk7uNnQHSZJ+x19ciP4RS2qjjZNro42kNtpY6jZ0B0lttHFyt6E7SJL0O/7iQvSPWFIbbZxcG20ktdHGUrehO0hqo42Tuw3dQZKk3/EXF6J/xJLaaOPk2mgjqY02lroN3UFSG22c3G3oDpIk/Y6/uBD9I5bURhsn10YbSW20sdRt6A6S2mjj5G5Dd5Ak6Xf8xYXoH7GkNto4uTbaSGqjjaVuQ3eQ1EYbJ3cbuoMkSb/jLy5E/4gltdHGybXRRlIbbSx1G7qDpDbaOLnb0B0kSfodf3Eh+kcsqY02Tq6NNpLaaGOp29AdJLXRxsndhu4gSdLv+IsL0T9iSW20cXJttJHURhtL3YbuIKmNNk7uNnQHSZJ+x19ciP4RS2qjjZNro42kNtpIaqONpdbRmZN0Nnpze986OnOStvgiIfrIk9po4+TaaCOpjTaS2mhjqXV05iSdjd7c3reOzpykLb5IiD7ypDbaOLk22khqo42kNtpYah2dOUlnoze3962jMydpiy8Soo88qY02Tq6NNpLaaCOpjTaWWkdnTtLZ6M3tfevozEna4ouE6CNPaqONk2ujjaQ22khqo42l1tGZk3Q2enN73zo6c5K2+CIh+siT2mjj5NpoI6mNNpLaaGOpdXTmJJ2N3tzet47OnKQtvkiIPvKkNto4uTbaSGqjjaQ22lhqHZ05SWejN7f3raMzJ2mLLxKijzypjTZOro02ktpoI6mNNpZaR2dO0tnoze196+jMSdrii4ToI09qo42Ta6ONpDbaSGqjjaXW0ZmTdDZ6c3vfOjpzkrb4IiH6yJPaaOPk2mgjqY02ktpoY6l1dOYknY3e3N63js6cpC2+SIg+8qQ22ji5NtpIaqONpDbaWGodnTlJZ6M3t/etozMnaYsvEqKPPKmNNk6ujTaS2mgjqY02llpHZ07S2ejN7X3r6MxJ2uKLhOgjT2qjjZNro42kNtpIaqONpdbRmZN0Nnpze986OnOStvgiIfrIk9po4+TaaCOpjTaS2mhjqXV05iSdjd7c3reOzpykLb5IiD7ypDbaOLk22khqo42kNtpYah2dOUlnoze3962jMydpiy8Soo88qY02Tq6NNpLaaCOpjTaWWkdnTtLZ6M3tfevozEna4ouE6CNPaqONk2ujjaQ22khqo42l1tGZk3Q2enN73zo6c5K2+CIh+siT2mjj5NpoI6mNNpLaaGOpdXTmJJ2N3tzet47OnKQtvkiIPvKkNto4uTbaSGqjjaQ22lhqHZ05SWejN7f3raMzJ2mLLxKijzypjTZOro02ktpoI6mNNpZaR2dO0tnoze196+jMSdrii4ToI0/SFnqjpDbaOLk22ji5NtpIaqONpdpoI2kdnXmpNtpI0hZfJEQfeZK20BsltdHGybXRxsm10UZSG20s1UYbSevozEu10UaStvgiIfrIk7SF3iipjTZOro02Tq6NNpLaaGOpNtpIWkdnXqqNNpK0xRcJ0UeepC30RklttHFybbRxcm20kdRGG0u10UbSOjrzUm20kaQtvkiIPvIkbaE3SmqjjZNro42Ta6ONpDbaWKqNNpLW0ZmXaqONJG3xRUL0kSdpC71RUhttnFwbbZxcG20ktdHGUm20kbSOzrxUG20kaYsvEqKPPElb6I2S2mjj5Npo4+TaaCOpjTaWaqONpHV05qXaaCNJW3yREH3kSdpCb5TURhsn10YbJ9dGG0lttLFUG20kraMzL9VGG0na4ouE6CNP0hZ6o6Q22ji5Nto4uTbaSGqjjaXaaCNpHZ15qTbaSNIWXyREH3mSttAbJbXRxsm10cbJtdFGUhttLNVGG0nr6MxLtdFGkrb4IiH6yJO0hd4oqY02Tq6NNk6ujTaS2mhjqTbaSFpHZ16qjTaStMUXCdFHnqQt9EZJbbRxcm20cXJttJHURhtLtdFG0jo681JttJGkLb5IiD7yJG2hN0pqo42Ta6ONk2ujjaQ22liqjTaS1tGZl2qjjSRt8UVC9JEnaQu9UVIbbZxcG22cXBttJLXRxlJttJG0js68VBttJGmLLxKijzxJW+iNktpo4+TaaOPk2mgjqY02lmqjjaR1dOal2mgjSVt8kRB95EnaQm+U1EYbJ9dGGyfXRhtJbbSxVBttJK2jMy/VRhtJ2uKLhOgjT9IWeqOkNto4uTbaOLk22khqo42l2mgjaR2deak22kjSFl8kRB95krbQGyW10cbJtdHGybXRRlIbbSzVRhtJ6+jMS7XRRpK2+CIh+siTtIXeKKmNNk6ujTZOro02ktpoY6k22khaR2deqo02krTFFwnRR56kLfRGSW20cXJttHFybbSR1EYbS7XRRtI6OvNSbbSRpC2+SIg+crOnbkN3kLSOzrzUOjpzkrbQGyW10cZSOpsvHKIfjdlTt6E7SFpHZ15qHZ05SVvojZLaaGMpnc0XDtGPxuyp29AdJK2jMy+1js6cpC30RklttLGUzuYLh+hHY/bUbegOktbRmZdaR2dO0hZ6o6Q22lhKZ/OFQ/SjMXvqNnQHSevozEutozMnaQu9UVIbbSyls/nCIfrRmD11G7qDpHV05qXW0ZmTtIXeKKmNNpbS2XzhEP1ozJ66Dd1B0jo681Lr6MxJ2kJvlNRGG0vpbL5wiH40Zk/dhu4gaR2deal1dOYkbaE3SmqjjaV0Nl84RD8as6duQ3eQtI7OvNQ6OnOSttAbJbXRxlI6my8coh+N2VO3oTtIWkdnXmodnTlJW+iNktpoYymdzRcO0Y/G7Knb0B0kraMzL7WOzpykLfRGSW20sZTO5guH6Edj9tRt6A6S1tGZl1pHZ07SFnqjpDbaWEpn84VD9KMxe+o2dAdJ6+jMS62jMydpC71RUhttLKWz+cIh+tGYPXUbuoOkdXTmpdbRmZO0hd4oqY02ltLZfOEQ/WjMnroN3UHSOjrzUuvozEnaQm+U1EYbS+lsvnCIfjRmT92G7iBpHZ15qXV05iRtoTdKaqONpXQ2XzhEPxqzp25Dd5C0js681Do6c5K20BsltdHGUjqbLxyiH43ZU7ehO0haR2deah2dOUlb6I2S2mhjKZ3NFw7Rj8bsqdvQHSStozMvtY7OnKQt9EZJbbSxlM7mC4foR2P21G3oDpLW0ZmXWkdnTtIWeqOkNtpYSmfzhSVJkqQP+Qe5JEmS9CH/IJckSZI+5B/kkiRJ0of8g1ySJEn6kH+QS5IkSR/yD3JJkiTpQ/5BLkmSJH3IP8glSZKkD/kHuSRJkvQh/yCXJEmSPuQf5JIkSdKH/INckiRJ+pB/kEuSJEkf8g9ySZIk6UP+QS5JkiR9yD/IJUmSpA/5B7kkSZL0If8glyRJkj7kH+SSJEnSh/yDXJIkSfqQf5BLkiRJH/IPckmSJOlD/kEuSZIkfcg/yCVJkqQP+Qe5JEmS9CH/IJckSZI+5B/kkiRJ0of8g1ySJEn6kH+QS5IkSR/yD3JJkiTpQ/5BLkmSJH3IP8glSZKkD/kHuSRJkvQh/yCXJEmSPuQf5JIkSdKH/INckiRJ+pB/kEuSJEkf8g9ySZIk6UP+QS5JkiR9yD/IJUmSpA/5B7kkSZL0If8glyRJkj7kH+SSJEnSh/yDXJIkSfqQf5BLkiRJH/IPckmSJOlD/kEuSZIkfcg/yCVJkqQP+Qe5JEmS9CH/IJckSZI+5B/kkiRJ0of8g1ySJEn6kH+QS5IkSR/yD3JJkiTpQ/5BLkmSJH3IP8glSZKkD/kHuSRJkvQh/yCXJEmSPuQf5JIkSdKH/INckiRJ+pB/kEuSJEkf8g9ySZIk6UP+QS5JkiR9yD/IJUmSpA/5B7kkSZL0If8glyRJkj7kH+SSJEnSh/yDXJIkSfqQf5BLkiRJH/IPckmSJOlD/kEuSZIkfcg/yCVJkqQP+Qe5JEmS9CH/IJckSZI+5B/kkiRJ0of8g1ySJEn6kH+QS5IkSR/yD3JJkiTpQ/5BLkmSJH3m//7v/wE9SIjnicdHrgAAAABJRU5ErkJggg=="
    Dim s As String = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjExNUY0NDI2NjE3QTc5MzhCRTFCQTA2REJFRTkxQTQyNzU4NEVEQUIiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJFVjlFSm1GNmVUaS1HNkJ0dnVrYVFuV0U3YXMifQ.eyJkYXRhIjoie1wiU2VsbGVyR3N0aW5cIjpcIjI5QUFGQ0Q1ODYyUjAwMFwiLFwiQnV5ZXJHc3RpblwiOlwiMzdCWk5QTTk0MzBNMWtsXCIsXCJEb2NOb1wiOlwiSE9NRVRFU1Q3OTBcIixcIkRvY1R5cFwiOlwiSU5WXCIsXCJEb2NEdFwiOlwiMDcvMDMvMjAyMFwiLFwiVG90SW52VmFsXCI6MCxcIkl0ZW1DbnRcIjoxLFwiTWFpbkhzbkNvZGVcIjpcIjEwMDFcIixcIklyblwiOlwiNzM3MDgyOTUyNzZkMjViOTA3NWRmODE1OTg0Zjk3ZDVjZjZiNGQ1Y2Y5MmE3MmZiNGJjYmZiYjI4NDdjMmZmNFwifSIsImlzcyI6Ik5JQyJ9.lmZvmuJnJ4nXzGXdAESMJ_bX92AJOv_yFMV2QMuWXOOXqNGdnMFBthqZYUu4spH_g6tISYxVHdNWadnNSpHzS0NOttVG_qNSLCdoe5J06RRdyvrg7NQSeVWqveNmOFmGMYqCqGcqCR4SXmvPrcgAxyj5IStInBWDOPc9SoB0HtPAo0HZIDdQ49VpQJxlJRUL72akUc__O0cZGGwmUsKeNT4h6qIhvMpSCLI3muzJ2KMAZ-cIWpgIULuaeldfxghZxoFGamWwohSSU85Bpt4T5-vj_txzq4AubFKevSkRm3C1C_JC5ZKuRicx_0ZEflGhkeUOQ6V2BMNQVxt49pZ7Vw"
    Dim privatesub As String = "iVBORw0KGgoAAAANSUhEUgAAAFYAAAAQCAYAAACMV4iGAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAF9SURBVFhH7ZUBbsMgDEVzqNwo58lxeplehtnUn3xct6QZaOrEk9ACGPP9sbol9eKe0irZtpvN/xGb1PVpWZWxmmCh8ZFJA4zd184PZRpLjZutN+hibElgInb5+1d0NfYX9fQ1VuDCbvK6216/OGJ1D2tsxF3iF8nBtWjsKuv4xjk+m8/ROkYxxUzC+inzG8ZGTYV53pMJ7oP+d0jYQZXcEkFINoFMykaX4AdRh2lOLsY/XsEVo7zqWJ/D3/GK8mDusZUqp9Oie+Vnw/Za90nIQU5Agw9HRnoiI7hDc2EQqEgs36eDj4fGWmH+3BljQWRwy9imLoccOfAJmKvGZpFWgO777i1zV4wS5pN51HFX0PuR//uMFbKhsg6DMyYexmp+7SI+zt3OsCGXcfdrTnyrXtZS+SIfXmeEhBxcNRZCeFSxJsafh5k61MCn+614xPjuxvqpDjYNPFgP/8P0WvSbzxUdb5CwyQimsYOYxg5iGjuIaewgprGDmMYOIaUfcowwNHhM8s0AAAAASUVORK5CYII="
    Dim x() As Byte = Encoding.UTF8.GetBytes(s)
    Dim s64 As String = Convert.ToBase64String(x)
    qrimg.ImageUrl = "data:image/png;base64," & s64



    Dim qrGenerator As New QRCodeGenerator()

    Dim qrCode As QRCodeGenerator.QRCode = qrGenerator.CreateQrCode("Hello, I am Lalit Gupta", QRCodeGenerator.ECCLevel.Q)
    Dim imgBarCode As New System.Web.UI.WebControls.Image()
    imgBarCode.Height = 150
    imgBarCode.Width = 150
    Using bitMap As Bitmap = qrCode.GetGraphic(20)
      Using ms As New MemoryStream()
        bitMap.Save(ms, System.Drawing.Imaging.ImageFormat.Png)
        Dim byteImage As Byte() = ms.ToArray()
        imgBarCode.ImageUrl = "data:image/png;base64," + Convert.ToBase64String(byteImage)
      End Using
      form1.Controls.Add(imgBarCode)
    End Using

  End Sub

  Public Class TokenRequest
    Public Property username As String = "testeway@mastersindia.co"
    Public Property password As String = "Test@1234"
    Public Property client_id As String = "fIXefFyxGNfDWOcCWn"
    Public Property client_secret As String = "QFd6dZvCGqckabKxTapfZgJc"
    Public Property grant_type As String = "password"
  End Class
End Class
Public Class clearTaxRequest
  Public Sub New()
    Dim x As New cItemList
    ItemList.Add(x)
  End Sub
  Public Property Version As String = "1.01"
  Public Property TranDtls As New cTranDtls
  Public Property DocDtls As New cDocDtls
  Public Property SellerDtls As New cSellerDtls
  Public Property BuyerDtls As New cBuyerDtls
  Public Property ItemList As New List(Of cItemList)
  Public Property ValDtls As New cValDtls


  Public Class cTranDtls
    Public Property TaxSch As String = "GST"
    Public Property SupTyp As String = "B2B"
    Public Property RegRev As String = "Y"
  End Class
  Public Class cDocDtls
    Public Property Typ As String = "INV"
    Public Property No As String = "HOMELG005"
    Public Property Dt As String = "2020-03-12"
  End Class
  Public Class cSellerDtls
    Public Property Gstin As String = "29AAFCD5862R000"
    Public Property LglNm As String = "TAN TEST NI"
    Public Property TrdNm As String = "TAN TEST NI"
    Public Property Addr1 As String = "TEST2"
    Public Property Addr2 As String = "TEST2"
    Public Property Loc As String = "GANDHINAGAR"
    Public Property Pin As String = "560002"
    Public Property State As String = "KARNATAKA"
    Public Property Ph As String = "9999999999"
    Public Property Em As String = "ABC@GMAIL.COM"
  End Class
  Public Class cBuyerDtls
    Public Property Gstin As String = "37BZNPM9430M1kl"
    Public Property LglNm As String = "TAN TEST NI"
    Public Property Pos As String = "37"
    Public Property Addr1 As String = "TEST2"
    Public Property Addr2 As String = "TEST2"
    Public Property Loc As String = "GANDHINAGAR"
    Public Property Pin As String = "560002"
    Public Property State As String = "KARNATAKA"
    Public Property Ph As String = "9999999999"
    Public Property Em As String = "ABC@GMAIL.COM"
  End Class
  Public Class cItemList
    Public Property SlNo As String = "1"
    Public Property IsServc As String = "N"
    Public Property PrdDesc As String = "dfdfsdf"
    Public Property HsnCd As String = "1001"
    Public Property Qty As String = "10"
    Public Property Unit As String = "bag"
    Public Property UnitPrice As String = "10"
    Public Property TotAmt As String = "151"
    Public Property Discount As String = "0"
    Public Property AssAmt As String = "151"
    Public Property GstRt As String = "10"
    Public Property SgstAmt As String = "0"
    Public Property IgstAmt As String = "10"
    Public Property CgstAmt As String = "0"
    Public Property CesRt As String = "15"
    Public Property CesAmt As String = "123.89"
    Public Property CesNonAdvlAmt As String = "0"
    Public Property StateCesRt As String = "36"
    Public Property StateCesAmt As String = "151"
    Public Property StateCesNonAdvlAmt As String = "0"
    Public Property OthChrg As String = "0"
    Public Property TotItemVal As String = "100"
  End Class

  Public Class cValDtls
    Public Property AssVal As String = "100"
    Public Property CgstVal As String = "0"
    Public Property SgstVal As String = "0"
    Public Property IgstVal As String = "0"
    Public Property CesVal As String = "15"
    Public Property StCesVal As String = "36"
    Public Property RndOffAmt As String = "0"
    Public Property TotInvVal As String = "0"
  End Class

End Class
Public Class ClearTaxResponse
  Public Property Success As String = ""
  Public Property AckNo As String = ""
  Public Property AckDt As String = ""
  Public Property Irn As String = ""
  Public Property SignedInvoice As String = ""
  Public Property SignedQRCode As String = ""
  Public Property Status As String = ""
End Class
Public Class ClearTaxError
  Public Property Success As String = ""
  Public Property ErrorDetails As New List(Of cErrorDetails)
  Public Class cErrorDetails
    Public Property error_code As String = ""
    Public Property error_message As String = ""
    Public Property error_source As String = ""

  End Class
End Class

Public Class MasterIndiaOLD
  Public Class eblRequest
    Public Property access_token As String = ""
    Public Property user_gstin As String = ""
    Public Property data_source As String = ""
    Public Property transaction_details As New ctransaction_details
    Public Property document_details As New cdocument_details
    Public Property seller_details As New cseller_details
    Public Property buyer_details As New cbuyer_details
    Public Property dispatch_details As New cdispatch_details
    Public Property ship_details As New cship_details
    Public Property export_details As New cexport_details
    Public Property payment_details As New cpayment_details
    Public Property reference_details As New creference_details
    Public Property value_details As New cvalue_details
    Public Property item_list As New List(Of citem_list)
    Sub New()
      item_list.Add(New citem_list)
    End Sub

  End Class
  Public Class ctransaction_details
    Public Property category_of_transaction As String = ""
    Public Property charge_type As String = ""
    Public Property transaction_type As String = ""
    Public Property ecommerce_transaction As String = ""
    Public Property ecommerce_gstin As String = ""
  End Class
  Public Class cdocument_details
    Public Property document_type As String = ""
    Public Property document_number As String = ""
    Public Property document_date As String = ""
    Public Property original_document_number As String = ""
  End Class
  Public Class cseller_details
    Public Property gstin As String = ""
    Public Property trade_name As String = ""
    Public Property building_number As String = ""
    Public Property building_name As String = ""
    Public Property floor_number As String = ""
    Public Property location As String = ""
    Public Property district As String = ""
    Public Property pincode As String = ""
    Public Property state_code As String = ""
    Public Property phone_number As String = ""
    Public Property email As String = ""
  End Class
  Public Class cbuyer_details
    Public Property gstin As String = ""
    Public Property trade_name As String = ""
    Public Property building_number As String = ""
    Public Property building_name As String = ""
    Public Property floor_number As String = ""
    Public Property location As String = ""
    Public Property district As String = ""
    Public Property pincode As String = ""
    Public Property state_code As String = ""
    Public Property phone_number As String = ""
    Public Property email As String = ""
  End Class
  Public Class cdispatch_details
    Public Property gstin As String = ""
    Public Property trade_name As String = ""
    Public Property building_number As String = ""
    Public Property building_name As String = ""
    Public Property floor_number As String = ""
    Public Property location As String = ""
    Public Property district As String = ""
    Public Property pincode As String = ""
    Public Property state_code As String = ""
    Public Property phone_number As String = ""
    Public Property email As String = ""
  End Class
  Public Class cship_details
    Public Property gstin As String = ""
    Public Property trade_name As String = ""
    Public Property building_number As String = ""
    Public Property building_name As String = ""
    Public Property floor_number As String = ""
    Public Property location As String = ""
    Public Property district As String = ""
    Public Property pincode As String = ""
    Public Property state_code As String = ""
    Public Property phone_number As String = ""
    Public Property email As String = ""
  End Class
  Public Class cexport_details
    Public Property export_category As String = ""
    Public Property ship_bill_number As String = ""
    Public Property ship_bill_date As String = ""
    Public Property country_code As String = ""
    Public Property foreign_currency As String = ""
    Public Property total_invoice_value_in_foreign_currency As String = ""
    Public Property port_code As String = ""
    Public Property export_payment As String = ""
  End Class
  Public Class cpayment_details
    Public Property account_details As String = ""
    Public Property paid_balance_amount As String = ""
    Public Property credit_days As String = ""
    Public Property credit_transfer As String = ""
    Public Property direct_debit As String = ""
    Public Property branch_or_ifsc As String = ""
    Public Property payment_mode As String = ""
    Public Property payee_name As String = ""
    Public Property payment_due_date As String = ""
    Public Property payment_instruction As String = ""
    Public Property payment_term As String = ""
  End Class
  Public Class creference_details
    Public Property contract_reference_number As String = ""
    Public Property other_reference As String = ""
    Public Property invoice_period_start_date As String = ""
    Public Property invoice_period_end_date As String = ""
    Public Property invoice_reference_number As String = ""
    Public Property invoice_remarks As String = ""
    Public Property vendor_po_reference_number As String = ""
    Public Property preceding_invoice_date As String = ""
    Public Property preceding_invoice_number As String = ""
    Public Property project_reference_number As String = ""
    Public Property receipt_advice_number As String = ""
    Public Property batch_reference_number As String = ""
  End Class
  Public Class cvalue_details
    Public Property total_assessable_value As String = ""
    Public Property total_cgst_value As String = ""
    Public Property total_sgst_value As String = ""
    Public Property total_igst_value As String = ""
    Public Property total_cess_value As String = ""
    Public Property total_cess_nonadvol_value As String = ""
    Public Property total_invoice_value As String = ""
    Public Property total_cess_value_of_state As String = ""
    Public Property discount As String = ""
    Public Property other_charge As String = ""
  End Class
  Public Class citem_list
    Public Property product_name As String = ""
    Public Property product_description As String = ""
    Public Property hsn_code As String = ""
    Public Property bar_code As String = ""
    Public Property quantity As String = ""
    Public Property free_quantity As String = ""
    Public Property unit As String = ""
    Public Property unit_price As String = ""
    Public Property total_amount As String = ""
    Public Property discount As String = ""
    Public Property other_charge As String = ""
    Public Property assessable_value As String = ""
    Public Property cgst_rate As String = ""
    Public Property sgst_rate As String = ""
    Public Property igst_rate As String = ""
    Public Property cess_rate As String = ""
    Public Property cess_nonadvol_value As String = ""
    Public Property state_cess_rate As String = ""
    Public Property total_item_value As String = ""
    Public Property batch_details As String = ""
    Public Property name As String = ""
    Public Property expiry_date As String = ""
    Public Property warranty_date As String = ""
  End Class
  Public Class eblResponse
    Public Property message As eblMessage = New eblMessage
    Public Property errorMessage As String = ""
    Public Property status As String = "Success"
    Public Property code As String = "200"
    Public Property requestId As String = ""
  End Class
  Public Class eblMessage
    Public Property AckNo As String = ""
    Public Property AckDt As String = ""
    Public Property Irn As String = ""
    Public Property SignedInvoice As String = ""
    Public Property SignedQRCode As String = ""
    Public Property Status As String = ""
    Public Property [error] As Boolean = False
  End Class
  Public Class eblError
    Public Property message As String = ""
    Public Property errorMessage As String = "2150: Duplicate IRN"
    Public Property status As String = "Failed"
    Public Property code As String = "204"
    Public Property requestId As String = ""
  End Class

End Class

Public Class MasterIndia
  Public Property access_token As String = "a78e74508f285f5cd120716b81d8e91f2af96326"
  Public Property user_gstin As String = "09AAAPG7885R002"
  Public Property data_source As String = "erp"
  Public Property transaction_details As New ctransaction_details
  Public Property document_details As New cdocument_details
  Public Property seller_details As New cseller_details
  Public Property buyer_details As New cbuyer_details
  Public Property dispatch_details As New cdispatch_details
  Public Property ship_details As New cship_details
  Public Property export_details As New cexport_details
  Public Property payment_details As New cpayment_details
  Public Property reference_details As New creference_details
  Public Property additional_document_details As New List(Of cadditional_document_details)
  Public Property value_details As New cvalue_details
  Public Property ewaybill_details As New cewaybill_details
  Public Property item_list As New List(Of citem_list)
  Sub New()
    additional_document_details.Add(New cadditional_document_details)
    item_list.Add(New citem_list)
  End Sub

  Public Class ctransaction_details
      Public Property supply_type As String = "B2B"
      Public Property charge_type As String = "N"
      Public Property ecommerce_gstin As String = ""
    End Class
  Public Class cdocument_details
    Public Property document_type As String = "INV"
    Public Property document_number As String = "ISGEC001"
    Public Property document_date As String = "09/03/2020"
  End Class
  Public Class cseller_details
    Public Property gstin As String = "09AAAPG7885R002"
    Public Property legal_name As String = "MastersIndia UP"
    Public Property trade_name As String = "MastersIndia UP"
    Public Property address1 As String = "Vila"
    Public Property address2 As String = "Vila"
    Public Property location As String = "Noida"
    Public Property pincode As String = 201301
    Public Property state_code As String = "UTTAR PRADESH"
    Public Property phone_number As String = 9876543231
    Public Property email As String = ""
  End Class
  Public Class cbuyer_details
    Public Property gstin As String = "05AAAPG7885R002"
    Public Property legal_name As String = "MastersIndia UT"
    Public Property trade_name As String = "MastersIndia UT"
    Public Property address1 As String = "Kila"
    Public Property address2 As String = "Kila"
    Public Property location As String = "Nainital"
    Public Property pincode As String = 110010
    Public Property place_of_supply As String = "9"
    Public Property state_code As String = "UTTARAKHAND"
    Public Property phone_number As String = 9876543231
    Public Property email As String = ""
  End Class
  Public Class cdispatch_details
    Public Property company_name As String = "MastersIndia UP"
    Public Property address1 As String = "Vila"
    Public Property address2 As String = "Vila"
    Public Property location As String = "Noida"
    Public Property pincode As String = 201301
    Public Property state_code As String = "UTTAR PRADESH"
  End Class
  Public Class cship_details
    Public Property gstin As String = "05AAAPG7885R002"
    Public Property legal_name As String = "MastersIndia UT"
    Public Property trade_name As String = "MastersIndia UT"
    Public Property address1 As String = "Kila"
    Public Property address2 As String = "Kila"
    Public Property location As String = "Nainital"
    Public Property pincode As String = 110010
    Public Property state_code As String = "UTTARAKHAND"
  End Class
  Public Class cexport_details
    Public Property ship_bill_number As String = "qwe1233"
    Public Property ship_bill_date As String = "08/02/2020"
    Public Property country_code As String = "IN"
    Public Property foreign_currency As String = "INR"
    Public Property refund_claim As String = "N"
    Public Property port_code As String = "232434"
  End Class
  Public Class cpayment_details
    Public Property bank_account_number As String = "Account Details"
    Public Property paid_balance_amount As String = 100
    Public Property credit_days As String = 2
    Public Property credit_transfer As String = "Credit Transfer"
    Public Property direct_debit As String = "Direct Debit"
    Public Property branch_or_ifsc As String = "KKK000180"
    Public Property payment_mode As String = "CASH"
    Public Property payee_name As String = "Payee Name"
    Public Property payment_due_date As String = "08/02/2020"
    Public Property payment_instruction As String = "Payment Instruction"
    Public Property payment_term As String = "Terms of Payment"
  End Class
  Public Class creference_details
    Public Property invoice_remarks As String = "Invoice Remarks"
    Public Property invoice_period_start_date As String = "2020-01-01"
    Public Property invoice_period_end_date As String = "2020-01-30"
    Public Property preceding_document_details As New List(Of cpreceding_document_details)
    Public Property contract_details As New List(Of ccontract_details)
    Sub New()
      preceding_document_details.Add(New cpreceding_document_details)
      contract_details.Add(New ccontract_details)
    End Sub
  End Class
  Public Class cpreceding_document_details
    Public Property reference_of_original_invoice As String = "CFRT/0006"
    Public Property preceding_invoice_date As String = "08/02/2020"
    Public Property other_reference As String = "2334"
  End Class
  Public Class ccontract_details
    Public Property receipt_advice_number As String = "aaa"
    Public Property receipt_advice_date As String = "10/02/2020"
    Public Property batch_reference_number As String = "2334"
    Public Property contract_reference_number As String = "2334"
    Public Property other_reference As String = "2334"
    Public Property project_reference_number As String = "2334"
    Public Property vendor_po_reference_number As String = "233433454545"
    Public Property vendor_po_reference_date As String = "10/02/2020"
  End Class
  Public Class cadditional_document_details
    Public Property supporting_document_url As String = ""
    Public Property supporting_document As String = "india"
    Public Property additional_information As String = "india"
  End Class
  Public Class cvalue_details
    Public Property total_assessable_value As String = 1
    Public Property total_cgst_value As String = 0
    Public Property total_sgst_value As String = 0
    Public Property total_igst_value As String = 0.01
    Public Property total_cess_value As String = 0
    Public Property total_cess_nonadvol_value As String = 0
    Public Property total_invoice_value As String = 1.01
    Public Property total_cess_value_of_state As String = 0
    Public Property round_off_amount As String = 0
    Public Property total_invoice_value_additional_currency As String = 0
  End Class
  Public Class cewaybill_details
    Public Property transporter_id As String = "05AAABB0639G1Z8"
    Public Property transporter_name As String = "Jay Trans"
    Public Property transportation_mode As String = "1"
    Public Property transportation_distance As String = "120"
    Public Property transporter_document_number As String = "1230"
    Public Property transporter_document_date As String = "08/02/2020"
    Public Property vehicle_number As String = "PQR1234"
    Public Property vehicle_type As String = "R"
  End Class
  Public Class citem_list
    Public Property item_serial_number As String = "8965"
    Public Property product_description As String = "Wheat desc"
    Public Property is_service As String = "N"
    Public Property hsn_code As String = "1001"
    Public Property bar_code As String = "1212"
    Public Property quantity As String = 1
    Public Property free_quantity As String = 0
    Public Property unit As String = "KGS"
    Public Property unit_price As String = 1
    Public Property total_amount As String = 1
    Public Property pre_tax_value As String = 0
    Public Property discount As String = 0
    Public Property other_charge As String = 0
    Public Property assessable_value As String = 1
    Public Property gst_rate As String = 0
    Public Property igst_amount As String = 0
    Public Property cgst_amount As String = 1
    Public Property sgst_amount As String = 0
    Public Property cess_rate As String = 0
    Public Property cess_amount As String = 0
    Public Property cess_nonadvol_amount As String = 0
    Public Property state_cess_rate As String = 0
    Public Property state_cess_amount As String = 0
    Public Property state_cess_nonadvol_amount As String = 0
    Public Property total_item_value As String = 1
    Public Property country_origin As String = "52"
    Public Property order_line_reference As String = "5236"
    Public Property product_serial_number As String = "14785"
    Public Property batch_details As New cbatch_details
    Public Property attribute_details As New List(Of cattribute_details)
    Sub New()
      attribute_details.Add(New cattribute_details)
    End Sub
  End Class
  Public Class cbatch_details
    Public Property name As String = "aaa"
    Public Property expiry_date As String = "10/02/2020"
    Public Property warranty_date As String = "20/02/2020"
  End Class
  Public Class cattribute_details
    Public Property item_attribute_details As String = "aaa"
    Public Property item_attribute_value As String = "147852"
  End Class
End Class
